name: Build libFMS test

on: [push, pull_request]

jobs:
  build2:
    runs-on: ubuntu-latest
    container:
      image: underwoo/ubuntu_libfms_gnu
      env:
        FCFLAGS: ''
        CC: "mpicc"
        FC: "mpif90"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare GNU autoconf for build
        run: |
          ls `nc-config --prefix`
          export NETCDF_ROOT=$(
          mkdir build && cd build
          cmake ..
          make
          make install