# This is a basic workflow to help you get started with Actions

name: libfms

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ user/mkl/github_actions ]
  pull_request:
    branches: [ user/mkl/github_actions ]

env:
  FC: gfortran
  CC: gcc
  CXX: gcc
  CMAKE_Fortran_COMPILER: mpif90
  CMAKE_C_COMPILER: mpicc
  CMAKE_CXX_COMPILER: mpicxx
  BASE_FLAGS: "-ffree-line-length-none -fno-range-check -fbacktrace"
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: cleanup 
        run: sudo apt autoremove netcdf-bin libnetcdf-dev libnetcdff-dev
      - name: install netcdf 
        run: sudo apt-get install netcdf-bin libnetcdf-dev libnetcdff-dev --fix-missing 
      - name: where is netcdf 
        run: nc-config --all  
      - name: get mpich
        run: sudo apt-get install -y mpich libmpich-dev
      - name: test env variables 
        with: 
          CMAKE_Fortran_FLAGS: ${env.BASE_FLAGS}
        run: echo ${CMAKE_Fortran_FLAGS}
      
  

